direccion:
    pattern:  /
    defaults: { _controller: "BusetaBodegaBundle:Direccion:index" }

direccion_show:
    pattern:  /{id}/show
    defaults: { _controller: "BusetaBodegaBundle:Direccion:show" }

direccion_new:
    pattern:  /new
    defaults: { _controller: "BusetaBodegaBundle:Direccion:new" }

direccion_create:
    pattern:  /create
    defaults: { _controller: "BusetaBodegaBundle:Direccion:create" }
    requirements: { _method: post }

direccion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BusetaBodegaBundle:Direccion:edit" }

direccion_update:
    pattern:  /{id}/update
    defaults: { _controller: "BusetaBodegaBundle:Direccion:update" }
    requirements: { _method: post|put }

direccion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BusetaBodegaBundle:Direccion:delete" }
    requirements: { _method: post|delete }
