generator: admingenerator.generator.doctrine
params:
    model: Buseta\NomencladorBundle\Entity\Combustible
    namespace_prefix: Buseta
    concurrency_lock: ~
    bundle_name: NomencladorBundle
    pk_requirement: ~
    fields:
      valor:
            label: Valor
      codigo:
            label: C칩digo
      descripcion:
            label: Descripci칩n
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Listado de combustibles
            display: [valor, codigo, descripcion]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
            display: [valor, codigo, descripcion]
    new:
        params:
            title: Adicionar nuevo combustible
            display: [valor, codigo, descripcion]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Usted est치 modificando el combustible: \"%object%\"|{ %object%: Combustible.valor }|"
            display: [valor, codigo, descripcion]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Usted est치 mostrando los datos del combustible: \"%object%\"|{ %object%: Combustible.valor }|"
            display: [valor, codigo, descripcion]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
