generator: admingenerator.generator.doctrine
params:
    model: Buseta\NomencladorBundle\Entity\Grupo
    namespace_prefix: Buseta
    concurrency_lock: ~
    bundle_name: NomencladorBundle
    pk_requirement: ~
    fields:
      valor:
            label: Valor
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Listado de grupos
            display: [valor]
            actions:
                new: ~
            object_actions:
                show: ~
                edit: ~
                delete: ~
    filters:
        params:
             display: [valor]
    new:
        params:
            title: Adicionar nuevo grupo
            display: [valor]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Usted está modificando el grupo: \"%object%\"|{ %object%: Grupo.valor }|"
            display: [valor]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Usted está mostrando los datos del grupo: \"%object%\"|{ %object%: Grupo.valor }|"
            display: [valor]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
